sudo: false
language: ruby
rvm: 2.2

install:
  - bundle install
  - curl -s https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt -o sbt
  - chmod +x sbt

script:
  - ./sbt run
  - bundle exec jekyll build
