sudo: false
language: ruby
rvm: 2.2

install:
  - bundle install
  - curl -s https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt -o sbt
  - chmod +x sbt

script:
  - ./sbt run
  - bundle exec jekyll build

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
